### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by GolanTrevize10** [CreditMutuelArkea/sonar-apigee-plugin#14]
Hi, we are trying to scan a webflow project with many xml files with SonarQube 7.9 and plugin version 2.1.0. We keep getting the error below. Obviously for a weblow project we don't need to run apigee plugin. So is it any way of fixing this memory issue or at least to disable the plugin for this specific project?

17:09:11 java.lang.OutOfMemoryError: GC overhead limit exceeded
17:09:11 	at org.apache.xerces.xni.XMLString.toString(Unknown Source)
17:09:11 	at org.apache.xerces.parsers.AbstractDOMParser.characters(Unknown Source)
17:09:11 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
17:09:11 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
17:09:11 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
17:09:11 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
17:09:11 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
17:09:11 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
17:09:11 	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
17:09:11 	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
17:09:11 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
17:09:11 	at org.sonarsource.analyzer.commons.xml.XmlParser.<init>(XmlParser.java:62)
17:09:11 	at org.sonarsource.analyzer.commons.xml.XmlFile.create(XmlFile.java:90)
17:09:11 	at com.arkea.satd.sonar.xml.ApigeeXmlSensor.execute(ApigeeXmlSensor.java:117)
17:09:11 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
17:09:11 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
17:09:11 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
17:09:11 	at org.sonar.scanner.sensor.ModuleSensorsExecutor$$Lambda$877/260794179.run(Unknown Source)
17:09:11 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
17:09:11 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
17:09:11 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
17:09:11 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
17:09:11 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
17:09:11 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
17:09:11 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
17:09:11 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
17:09:11 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
17:09:11 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
17:09:11 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
17:09:11 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
17:09:11 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
17:09:11 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)

**Comment by ntiss** [comment]
Unfortunately, the plugin has to store all XML files in memory during analysis because there are dependancies between different files. The behaviour is to store any unknow xml file in a "policy" map to consider all new policy names (in future releases of Apigee).
If your project contains a lot xml file, there are chances for the scanner to run out of memory, I agree.

In SonarQube, it seems that it's not possible anymore to choose a specific profile. As well, it's not possible to disable a plugin for a specific projet.

What you could do now (some ideas) : 
- tune java Xmx settings for the sonarqube-scanner
- try some ugly tricks through the admin API like : disable plugin / scan / re-enable plugin, or change the SonarWay Profile
- use a separated SonarQube instance for Apigee projects with the plugin, an another instance without the plugin for your other projects

Regards.
