### ISSUE TITLE
"An appropriate check for a message body was not found on the enclosing Step or Flow." raised for ExtractVariables policy after ServiceCallout

### ISSUE THREAD

**Issue by OllieReynolds** [CreditMutuelArkea/sonar-apigee-plugin#4]
ServiceCallout policy executes -- response is assigned to myServiceCalloutResponse in the policy using `<Response>myServiceCalloutResponse</Response>`

ExtractVariables policy executes -- retrieves field from myServiceCalloutResponse.content using `<JSONPath> `and `<Source clearPayload="false">myServiceCalloutResponse.content</Source>`

Violation is raised where the ExtractVariable policy gets executed during the flow (after the service callout) -- I think it is because it doesn't see a condition to check any of the below variables -- instead the condition in my flow to execute the ExtractVariables policy checks for the custom variable myServiceCalloutResponse written in the ServiceCallout.

- response.content
- response.form
- request.content
- request.form
- message.content
- message.form
- message.verb
- request.verb
- request.header.Content-Length
- response.header.Content-Length

Rule ID is: PO003

**Comment by ntiss** [comment]
Hello @OllieReynolds 
Thank you for reporting this. I'll take a look at this but it doesn't seem easy to fix.
For now, you can simply flag the issue as "Resolve as false positive" in Sonar itself once beeing logged in.

**Comment by eduandrade** [comment]
The same thing happens when extracting variables using **error.content** as the source.

If I use apigeelint this error is not reported. I checked their [code](https://github.com/apigeecs/bundle-linter/blob/master/lib/package/plugins/extractJSONConditionCheck.js) and the main difference I think is this part:
`if (sourceElement.length) {
      source = sourceElement[0].data;

      condRegExp = !source.match(condRegExp) ? source : condRegExp;
}`

If the source data doesn't match the regex condition it then uses the source element text as the regex condition.
 `var condRegExp = "(response.content|response.form|request.content|request.form|message.content|message.form|message.verb|request.verb)";`

I guess that's the reason apigeelint is more flexible in regards to this particular error.

Thanks for maintaining this plugin.

**Comment by ntiss** [comment]
Hello @OllieReynolds  and @eduandrade A quick update to inform that I'm currently working on a fix for this issue.
Many thanks to @eduandrade for providing the exact solution.

The fix will be released in a couple of days ou weeks due to the announcement process of plugins for SonarSource. I'll let you know when the RC-1 is available for tests.

**Comment by ntiss** [comment]
This is issue has been fixed in the release 2.1.0.
Directly available in the marketplace with SQ 7.9+. 
Manual installation if you use SQ <7.9
